version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    volumes:
      - .:/usr/src/app
    environment:
      NODE_ENV: production
      PORT: 3000
      ORIGIN: http://localhost:3000
      SECRET: f282daa3f819c24c68fecfed2daa0905aa13470a
      RABBITMQ_URI: amqp://sjdonado:f8faf60a6676005066c721926b4d7da7@rabbitmq:5672/chatbot
      RABBITMQ_CLIENT_WS: ws://client:client@localhost:15675/ws
      REDIS_URI: redis://redis:6379
      BOT_QUEUE: botqueue_f8f219af60a66760050667
    ports:
      - 3000:3000
    depends_on:
      - redis
      - rabbitmq
      - bot
  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    volumes:
      - ./bot:/usr/src/app
    environment:
      NODE_ENV: production
      RABBITMQ_URI: amqp://bot:f8faf60a6676005066c721926b4d7da7@rabbitmq:5672/chatbot
      BOT_QUEUE: botqueue_f8f219af60a66760050667
    ports:
      - 3001:3001
    depends_on:
      - rabbitmq
  rabbitmq:
    image: rabbitmq:3
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: sjdonado
      RABBITMQ_DEFAULT_PASS: f8faf60a6676005066c721926b4d7da7
      RABBITMQ_DEFAULT_VHOST: chatbot
    ports:
      - 5672:5672
  redis:
    image: redis:buster
    ports:
      - 6379:6379